// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfMz0v5mfBb3Jzw99PJGn1Rt_7jrHRf9w',
    appId: '1:213924853523:web:5afccabaa31431a0988ce6',
    messagingSenderId: '213924853523',
    projectId: 'chat-hub-9d7e2',
    authDomain: 'chat-hub-9d7e2.firebaseapp.com',
    storageBucket: 'chat-hub-9d7e2.firebasestorage.app',
    measurementId: 'G-YLN83P4GS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByMqpMNrrJ1cL71HI1wnxaNdmOwnt7Ops',
    appId: '1:213924853523:android:fa8cf9e2fcad085e988ce6',
    messagingSenderId: '213924853523',
    projectId: 'chat-hub-9d7e2',
    storageBucket: 'chat-hub-9d7e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7YkddDVdZocLGdpPUbiCvnjKhJwJBW3E',
    appId: '1:213924853523:ios:d97669c7c6189cb8988ce6',
    messagingSenderId: '213924853523',
    projectId: 'chat-hub-9d7e2',
    storageBucket: 'chat-hub-9d7e2.firebasestorage.app',
    iosBundleId: 'com.builtbyusman.chathub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7YkddDVdZocLGdpPUbiCvnjKhJwJBW3E',
    appId: '1:213924853523:ios:79749766e47380c9988ce6',
    messagingSenderId: '213924853523',
    projectId: 'chat-hub-9d7e2',
    storageBucket: 'chat-hub-9d7e2.firebasestorage.app',
    iosBundleId: 'com.example.chathub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfMz0v5mfBb3Jzw99PJGn1Rt_7jrHRf9w',
    appId: '1:213924853523:web:3cdbe3405b01abad988ce6',
    messagingSenderId: '213924853523',
    projectId: 'chat-hub-9d7e2',
    authDomain: 'chat-hub-9d7e2.firebaseapp.com',
    storageBucket: 'chat-hub-9d7e2.firebasestorage.app',
    measurementId: 'G-NCN89S9WL5',
  );
}
